# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('temperature', models.IntegerField(max_length=3)),
                ('last_update', models.CharField(max_length=200)),
            ],
        ),
    ]
